"""管理后台:users加is_admin + app_settings/llm_groups/llm_models表

Revision ID: 4b247f0ab0a1
Revises: 2b695bf2f420
Create Date: 2026-06-30 15:29:19.879925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b247f0ab0a1'
down_revision: Union[str, Sequence[str], None] = '2b695bf2f420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(), server_default='', nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('llm_groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), server_default='', nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('llm_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('vision', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('cost', sa.Integer(), server_default='1', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['group_name'], ['llm_groups.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('llm_models')
    op.drop_table('llm_groups')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
