"""orders 删除 payment_method 字段（爱发电为唯一支付）

Revision ID: 70cb1ea464f2
Revises: c44aa7c8c5b7
Create Date: 2026-06-27 19:06:36.230770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70cb1ea464f2'
down_revision: Union[str, Sequence[str], None] = 'c44aa7c8c5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(), server_default=sa.text("'alipay'"), nullable=False))

    # ### end Alembic commands ###
