"""boot_failures 预览启动失败监控表

Revision ID: 7b9d371d4a69
Revises: ef94893b30e5
Create Date: 2026-07-07 16:36:20.156107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9d371d4a69'
down_revision: Union[str, Sequence[str], None] = 'ef94893b30e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boot_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), server_default='booting', nullable=False),
    sa.Column('kind', sa.String(), server_default='error', nullable=False),
    sa.Column('message', sa.Text(), server_default='', nullable=False),
    sa.Column('cross_origin_isolated', sa.Boolean(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boot_failures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boot_failures_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_boot_failures_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boot_failures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boot_failures_user_id'))
        batch_op.drop_index(batch_op.f('ix_boot_failures_session_id'))

    op.drop_table('boot_failures')
    # ### end Alembic commands ###
