"""users 加 tier/daily_used/daily_date 三列（付费第1步）

Revision ID: 824ed8891c69
Revises: 5ca68a943576
Create Date: 2026-06-17 13:23:46.620805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824ed8891c69'
down_revision: Union[str, Sequence[str], None] = '5ca68a943576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(), server_default='free', nullable=False))
        batch_op.add_column(sa.Column('daily_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('daily_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_date')
        batch_op.drop_column('daily_used')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
