"""boot_failures 增加 cold/prewarm 字段（冷热boot埋点）

Revision ID: c932b392335c
Revises: 7b9d371d4a69
Create Date: 2026-07-08 10:29:04.294606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c932b392335c'
down_revision: Union[str, Sequence[str], None] = '7b9d371d4a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boot_failures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cold', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prewarm', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boot_failures', schema=None) as batch_op:
        batch_op.drop_column('prewarm')
        batch_op.drop_column('cold')

    # ### end Alembic commands ###
