"""orders 审核字段 + 移除爱发电配置

Revision ID: ef94893b30e5
Revises: c941581b6eaa
Create Date: 2026-07-07 11:28:43.115886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef94893b30e5'
down_revision: Union[str, Sequence[str], None] = 'c941581b6eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pay_note', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###

    # 清理老库里已 seed 的爱发电配置行（ensure_seeded 只增不删，得在迁移里删）。
    op.execute("DELETE FROM app_settings WHERE key LIKE 'afdian_%'")


def downgrade() -> None:
    """Downgrade schema."""
    # 爱发电配置行不恢复（已无对应代码，回滚也没意义）。
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('pay_note')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
